[project]
name = "wakeworddetector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12, <3.14"
dependencies = [
    "datasets>=5.0.0",
    "ffmpeg>=1.4",
    "matplotlib>=3.11.0",
    "numpy>=2.5.0",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.0",
    "sounddevice>=0.5.5",
    "soundfile>=0.14.0",
    "tensorboard>=2.21.0",
    "torch>=2.13.0",
    "torchaudio>=2.11.0",
    "torchcodec>=0.14.0",
    "torchinfo>=1.8.0",
    "torchvision>=0.27.1",
    "tqdm>=4.68.3",
    "triton-xpu; sys_platform == 'linux' or sys_platform == 'win32'",
]

[tool.uv]
# Tells uv to only solve dependencies for platforms Intel Arc supports
environments = [
    "sys_platform == 'linux'",
    "sys_platform == 'win32'",
]

[[tool.uv.index]]
name = "pytorch-xpu"
url = "https://download.pytorch.org/whl/xpu"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-xpu", marker = "sys_platform == 'linux' or sys_platform == 'win32'" }]
torchaudio = [{ index = "pytorch-xpu", marker = "sys_platform == 'linux' or sys_platform == 'win32'" }]
torchvision = [{ index = "pytorch-xpu", marker = "sys_platform == 'linux' or sys_platform == 'win32'" }]
triton-xpu = [{ index = "pytorch-xpu", marker = "sys_platform == 'linux' or sys_platform == 'win32'" }]